- name: Setup app servers
  hosts: apiservers
  remote_user: ec2-user
  become: yes
  gather_facts: no
  tasks:
    - name: Install git
      yum: name=git state=latest
    - name: install epel-repository
      yum: name=epel-release
    - name: install nodejs
      yum: name=nodejs
    - name: install npm
      yum: name=npm
